---
version: 0.2
env:
  shell: /bin/bash
  variables:
    PUBLIC_REGISTRY: public.ecr.aws/compose-x

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - if [ -z ${AWS_ACCOUNT_ID+x} ]; then AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account); fi
      - REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-$AWS_DEFAULT_REGION}.amazonaws.com/
      - (pip --version && pip install pip -U) || curl https://bootstrap.pypa.io/get-pip.py | python

  pre_build:
    commands:
      - echo Login to own ECR registry
      - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}
      - EPOCH=`date +'%s'`
      - IMAGE_TAG=${COMMIT_HASH:=$EPOCH}
      - echo Docker repository ${PUBLIC_REGISTRY}
      - echo Docker image tag $IMAGE_TAG
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${PUBLIC_REGISTRY}

  build:
    commands:
      - docker build -f docker/Dockerfile -t ${PUBLIC_REGISTRY}/kafka-lag-exporter:al2-${IMAGE_TAG} .
      - docker push ${PUBLIC_REGISTRY}/kafka-lag-exporter:al2-${IMAGE_TAG}
